apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas
  template:
    metadata:
      labels:
        app: reservas
    spec:
      containers:
      - name: reservas
        image: kevincastro25/reservas_service:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: reservas-service
spec:
  selector:
    app: reservas
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: NodePort
